/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orangebyte256_convexcopier_fillpolygonimpl_FillPolygonImpl */

#ifndef FillPolygonJNI
#define FillPolygonJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orangebyte256_convexcopier_fillpolygonimpl_FillPolygonImpl
 * Method:    fillPolygonJNI
 * Signature: ([II[I[III)V
 */
JNIEXPORT void JNICALL Java_com_orangebyte256_convexcopier_fillpolygonimpl_FillPolygonImpl_fillPolygonJNI
  (JNIEnv *, jobject, jintArray, jint, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
