/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orangebyte256_convexcopier_imageeditor_ImageEditor_fillPolygonJNI */

#ifndef FILL_POLYGON_JNI
#define FILL_POLYGON_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orangebyte256_convexcopier_imageeditor_ImageEditor_fillPolygonJNI
 * Method:    fillPolygonJNI
 * Signature: ([II[I[IIIII)V
 */
JNIEXPORT void JNICALL Java_com_orangebyte256_convexcopier_imageeditor_ImageEditor_fillPolygonJNI
  (JNIEnv *, jobject, jintArray, jint, jintArray, jintArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
